# Configuracion del Deployment del CRUD

apiVersion: apps/v1             # Versión de la Api
kind: Deployment                # Tipo de objeto: Despliegue
metadata:
  name: deployment-crud         # Nombre del despliegue
  labels:
    app: sistema-calificacion          
spec:
  selector:                     # Permite seleccionar un conjunto de objetos que los condicione     
    matchLabels:                # en este caso etiquetas que coincidan
      app: sistema-calificacion   
      tier: app-web             
  replicas: 7	                # Número de pods
  template:		                # plantilla para los contenedores
    metadata:
      labels:
        app: sistema-calificacion         # Etiqueta de la aplicación
        tier: app-web           # Etiqueta de nivel
    spec:
      containers:
      - name: sistema-calificacion                   # Nombre del contenedor
        image: pferhd7/apache2-crud:v5     # Imagen del contenedor
        ports: 
        - containerPort: 80               # Puerto del contenedor